name: log_to_secure_file
description: "A package to save and retrieve logs securely"
version: 1.0.0
homepage: https://github.com/icapps/log_to_secure_file

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_key_value_file_storage: ^0.1.0
  flutter_secure_file_storage: ^1.2.0
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
  flutter_lints: ^2.0.0